### ISSUE TITLE
min_density parameter deprecation in sklearn 0.16

### ISSUE THREAD

**Issue by mpearmain** [dclambert/pyensemble#2]
Not sure if you were still maintaining this code base base but now fails with sklearn 0.16.0 due to:

"The min_density parameter is deprecated as of version 0.14 and will be removed in 0.16.
  "and will be removed in 0.16.", DeprecationWarning)"

**Comment by dclambert** [comment]
Hi, thanks for the heads-up, I’ll take care of it.

**Comment by mpearmain** [comment]
Thanks

Locally, i've also added n_jobs=-1 to a lot of the classifiers to improve speed i.e Extratrees, sgd and RandomForest, not an issue but food for thought
